### ISSUE TITLE
Is it possible to style the backgroundcolor of the dateHeader?

### ISSUE THREAD

**Issue by raLaaaa** [JonasWanke/timetable#125]
I'd like to change the background color of the date header:

![image](https://user-images.githubusercontent.com/12799722/182344107-b932a26d-00dd-47c6-be59-42b01fb9b025.png)

I was looking into `dateHeaderStyleProvider` how ever there is no attribute for background color. Any hints where I have to look or whether is not possible right now?

**Comment by JonasWanke** [comment]
`DateHeader` doesn't have an option to set a background color, but you can customize the widget builder and wrap it in `ColoredBox`:

```dart
MultiDateTimetable<BasicEvent>(
  headerBuilder: (context, leadingWidth) =>
      MultiDateTimetableHeader<BasicEvent>(
    leading: SizedBox(
      width: leadingWidth,
      child: Center(child: WeekIndicator.forController(null)),
    ),
    dateHeaderBuilder: (context, date) => ColoredBox(
      color: myBackgroundColor,
      child: DateHeader(date),
    ),
  ),
);
```

If the background color should also apply to the week indicator, you can move the `ColoredBox` outside the `MultiDateTimetableHeader` instead of just the `DateHeader`

**Comment by raLaaaa** [comment]
Thank you @JonasWanke !
