### ISSUE TITLE
Is it possible to use a different weekdayIndicatorStyleProvider for the monthview then for the basic table?

### ISSUE THREAD

**Issue by raLaaaa** [JonasWanke/timetable#126]
I'd like to change the way days are labelled for the monthview compared to the basic view.
To be more specific:

![image](https://user-images.githubusercontent.com/12799722/182636952-3647e9bb-c933-43fe-bf79-28433302ebf8.png)

Dates above should be shorter. Is there an easy way to do this currently?
I was looking at `MonthWidgetStyle` and `MonthIndicatorStyle` and thought that the `label` attribute from the `MonthIndicatorStyle` might change that but it does not. The style is always fully inherited from the ` WeekdayIndicatorStyle`

**Comment by JonasWanke** [comment]
`MonthIndicator` is responsible for displaying the name of a single month (“August”, etc.) and is intended to be used, e.g., as the header of a `MonthWidget` which shows the grid of days shown in your screenshot. The column labels of `MonthWidget`, by default, are `WeekdayIndicator`s styled by the corresponding `WeekdayIndicatorStyle`. For customizing it, you could wrap the `MonthWidget` (or `CompactMonthTimetable` that creates these) in a `TimetableThemeData` where you overwrite the `weekdayIndicatorStyleProvider`.

Alternatively, you could use the `DateIndicator` of the `DateHeader` for the lower timetable instead of the `WeekdayIndicator` and give these two different styles:

```dart
TimetableThemeData(
  context,
  weekdayIndicatorStyleProvider: (date) => WeekdayIndicatorStyle(
    context,
    date,
    label: 'Shorter text for the upper timetable',
  ),
  dateHeaderStyleProvider: (date) => DateHeaderStyle(
    context,
    date,
    showWeekdayIndicator: false, // Only show the `DateIndicator`
  ),
  dateIndicatorStyleProvider: (date) => DateIndicatorStyle(
    context,
    date,
    label: 'Longer text for the lower timetable',
  ),
)
```

**Comment by raLaaaa** [comment]
Thank you. Good to know.
