### ISSUE TITLE
support different calendars

### ISSUE THREAD

**Issue by Jamalianpour** [JonasWanke/timetable#13]
hello,
how can I use persian calendar and date on this plugin?

**Comment by JonasWanke** [comment]
Thanks for filing this issue! Currently, <kbd>timetable</kbd> only supports the gregorian calendar. As it's based on [<kbd>time_machine</kbd>](https://github.com/Dana-Ferguson/time_machine) (which also supports three variants of the persian calendar), adding support for other calendar systems _should_ be relatively easy.

I can try implementing it starting next week, though I don't know how long I'll need for it.

**Comment by Jamalianpour** [comment]
thank you.
I will wait for it.

**Comment by JonasWanke** [comment]
Because [<kbd>time_machine</kbd>](https://pub.dev/packages/time_machine) is not maintained very actively and still hasn't published a null-safe version to pub.dev, I dropped the dependency on it as part of the big refactor/rewrite (issue: #17, PR: #69). Instead, Timetable now uses Dart's built-in `DateTime`. Unfortunately, this also means that supporting other calendars is now out of scope as Dart doesn't support them either.
